# Generated by Django 4.1.2 on 2022-12-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img_href', models.CharField(default='', max_length=500)),
                ('CheckBox', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=222)),
                ('Info', models.CharField(max_length=222)),
            ],
        ),
    ]
