# Generated by Django 4.1.2 on 2022-12-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_category_publishing_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='Info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author'),
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publishing_house')),
                ('Text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.text')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='publishing_house',
            field=models.ManyToManyField(through='app.Enrollment', to='app.publishing_house'),
        ),
    ]
